version: "3.3"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: "always"

  event-planner:
    build: .
    ports:
      - 3000:3000
    restart: "always"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://<user>:<Password>@localhost:27017/event-planner
      - JWT_ACCESS_TOKEN_SECRET="event-planner-backend-access-token"
      - JWT_ACCESS_TOKEN_EXPIRES=1
    command: npm start
